### ISSUE TITLE
bug: wrong type item prop in the #default slot

### ISSUE THREAD

**Issue by Yizack** [DerYeger/yeger#296] opened 2024-06-22 20:00 UTC
### Affected Packages

- [ ] @yeger/eslint-config
- [X] @yeger/vue-masonry-wall
- [ ] @yeger/vue2-masonry-wall
- [ ] vecti

### Description

Hello! I don't know exactly when I started having this issue and I don't know if this is a bug or I'm missing something, the component works as expected but the `item` prop in the `#default` slot isn't passing the correct type on my VSCode using Nuxt

![Screenshot 2024-06-22 144101](https://github.com/DerYeger/yeger/assets/16264115/3b7c993d-f34f-4e40-87a1-1ba57d69ced5)

I noticed that if I create a component using the code from [`vue-masonry-wall/src/masonry-wall.vue`](https://github.com/DerYeger/yeger/blob/main/packages/vue-masonry-wall/src/masonry-wall.vue) the types work but using the package gives the unknown type so I'm not sure if it's related to the build or something else I'm not doing.

Thanks for the support!

### Reproduction

https://github.com/Yizack/masonrywall-repro

### Additional context

- Typescript version: 5.4.5
- Nuxt version: 3.12.2
- @yeger/vue-masonry-wall version: 5.0.12
- Node version: 20.9.0
- PNPM version: 9.4.0
- VSCode: 1.90.2
- Windows 11

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment] 2024-06-23 12:30
Thanks for the report!
I've checked the implementation again, because I can reproduce your issue.
However, the generic type of the component is correctly assigned to the slot.
I'm not sure how to fix it, or if it is a build-tool/language-server related issue.

```ts
defineSlots<{
  default?: (props: {
    item: T
    column: number
    row: number
    index: number
  }) => any
}>()
```

**Comment by MartinX3** [comment] 2024-07-09 19:55
Also vue-tsc errors out because the type of `{ item }` becomes `unknown`.
Which results into `error TS2322: Type 'unknown' is not assignable to type 'Exampletype'.`

**Comment by Yizack** [comment] 2024-07-15 15:27
Potentially related issue:

- https://github.com/vuejs/language-tools/issues/4577

**Closed** 2024-08-06 18:32 UTC
Labels: bug

**Comment by DerYeger** [comment] 2024-08-06 18:53
`5.0.13` should fix the issue. I've adapted the documentation's code to catch similar issues in the future.

**Comment by MartinX3** [comment] 2024-08-07 07:33
@DerYeger Thank you but maybe that led to this new error

```
 Argument of type '{ columnWidth: number; gap: number; items: Gallery[] | undefined; }' is not assignable to parameter of type 'never'.
  > 19 |         <masonry-wall :column-width="280" :gap="16" :items="items[it]">
       |          ^^^^^^^^^^^^
  ```

**Comment by DerYeger** [comment] 2024-08-07 07:34
Hmm, `items: Gallery[] | undefined` seems incorrect, as `items` is required to be defined.

**Comment by MartinX3** [comment] 2024-08-07 07:42
That also doesn't work

```
 ERROR(vue-tsc)  Argument of type '{ columnWidth: number; gap: number; items: Gallery[]; }' is not assignable to parameter of type 'never'.
  > 19 |         <masonry-wall v-if="items[it]" :column-width="280" :gap="16" :items="items[it]">
       |          ^^^^^^^^^^^^
```

**Comment by DerYeger** [comment] 2024-08-07 07:48
Can you try importing `MasonryWall` in your SFC and using that instead of `masonry-wall`? If that doesn't work and typescript as well as vue-tsc are up-to-date I'd need a minimal reproduction to investigate. I have 2 projects using `5.0.13` and the error was fixed without the above issue.

**Comment by MartinX3** [comment] 2024-08-07 10:22
@DerYeger I tested around and found the reason.  
The Quasar Framework now uses a stricter tslint option.

This is causing it:
https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes 

So masonry-wall probably needs a better type definition somewhere?

**Comment by DerYeger** [comment] 2024-08-07 10:57
I'm not using `any` here, the issue is https://github.com/vuejs/core/issues/6532#issuecomment-2271817365

**Comment by MartinX3** [comment] 2024-08-07 11:02
oh, I thought because of https://github.com/DerYeger/yeger/blob/8a14de0d3a9103600deb1c69e926c7adc8454cf4/packages/vue-masonry-wall/src/masonry-wall.vue#L49

In my comment in the vuejs/core issue my problem was that I couldn't omit entries in `withDefaults`.
So I just set them `variable: undefined` there to fix this issue.

**Comment by DerYeger** [comment] 2024-08-07 11:04
See `https://blog.vuejs.org/posts/vue-3-3#typed-slots-with-defineslots` for the single `any` justification.

I'm using `withDefaults`, so `exactOptionalPropertyTypes: true` breaks the types for Vue.

**Comment by MartinX3** [comment] 2024-10-20 14:11
It's fixed with `https://vuejs.org/guide/components/props.html#reactive-props-destructure` and using `exactOptionalPropertyTypes: true` works fine.

`withDefaults` is deprecated since `vue 3.5`.
